version: 2
updates:
  # Monitor Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
  # Monitor Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10